### ISSUE TITLE
Problemas con open MP

### ISSUE THREAD

**Issue by jpperez5** [rudyjb24/IMT2112#2]
Estoy tratando de compilar el código de "hello_world.cpp" de la ayudantía 4 y me arroja el siguiente error 
![image](https://user-images.githubusercontent.com/53842675/65458315-b5fd2a80-de23-11e9-94f4-b7a8f688f8a4.png)
¿Por qué sucede?

**Comment by rudyjb24** [comment]
Tienes que compilar con un comando especial: g++ file.cpp -fopenmp 

Esta todo detallado en el archivo "Comandos Utiles.txt" de la ayudantia 4.

**Comment by jpperez5** [comment]
Gracias

**Comment by jpperez5** [comment]
Una última duda, ¿es posible utilizar el comando #pragma omp parallel más de una vez si quiero especificar más de una sección paralela en mi código?

**Comment by rudyjb24** [comment]
Sip
