### ISSUE TITLE
Open MP demora más que el código sin paralelizar

### ISSUE THREAD

**Issue by jpperez5** [rudyjb24/IMT2112#3]
Cuando intenté utilizar omp en el cálculo, el programa paralelizado demoró casi lo mismo que el programa original, e incluso podía llegar a demorarse más. ¿Por qué puede ser?

**Comment by rudyjb24** [comment]
Como estas midiendo el tiempo de ejecuccion?

**Comment by jpperez5** [comment]
Estoy usando clock como en las ayudantías. O sea, tengo un start = clock() y al final del código un end = clock()

**Comment by rudyjb24** [comment]
Recuerda que como dijimos en ayudantia, clock no devuelve el tiempo actual como el time de python, sino que devuelve CLOCKS_PER_SEC. En teoría esto tiene que ver con la operaciones por segundo, al tener varios cores, estas realizando mas operaciones por segundo que en la versión secuencial.

Usa mejor time que si funciona como el time de python.

**Comment by jpperez5** [comment]
Probé con time pero el resultado sólo me arroja enteros, por lo que no puedo ver tan claramente las diferencias de tiempos de ejecución

**Comment by rudyjb24** [comment]
Como estas declarando las variables donde guardas el time?

**Comment by jpperez5** [comment]
start = time(NULL)
...
...
...
end = time(NULL)

**Comment by rudyjb24** [comment]
Falta el tipo de variable de start y end.

**Comment by jpperez5** [comment]
fueron declaradas al inicio del archivo.
time_t start, end;
...
start = time(NULL)
...
end = time(NULL)

**Comment by rudyjb24** [comment]
Prueba haciendo un casting al momento de hacer la resta:

printf("\nNos demoramos %f seg\n", (float)(end-start));

**Comment by jpperez5** [comment]
hice la prueba y sigue arrojando enteros

**Comment by rudyjb24** [comment]
Veamoslo después de la ayudantia, te parece?

**Comment by jpperez5** [comment]
ok
