### ISSUE TITLE
Tarea 3

### ISSUE THREAD

**Issue by bjbarias** [rudyjb24/IMT2112#5]
Hola Rudy!
Quería saber si, dadas las circunstancias de lo que está pasando en Santiago, se va a dar un poco más de tiempo para la tarea 3 (por más que sea entrega no presencial, hay una tensión grande que no se si se está tomando en cuenta). Te lo pregunto, porque en otros ramos se discute lo mismo.
Desde ya muchas gracias,

Bernardo

**Comment by rudyjb24** [comment]
Bernardo, 

Entiendo perfectamente lo difícil que es tratar de concentrarse en tareas dado todo lo que está pasando. Voy a hablar con el profesor para tratar de darles más plazo. 

Cuidense,

Rudyard

**Comment by bjbarias** [comment]
Gracias Rudy!
