### ISSUE TITLE
rank 0 out of 1 processors

### ISSUE THREAD

**Issue by cafigueredo** [rudyjb24/IMT2112#6]
En el código hello_world.cpp de ayudantía al cambiar el numero de nodos, de tasks y de cpus-per-task en el job.sh hay problemas con los ranks y procesos y solo sale "rank 0 out of 1 processors"
¿Como podemos testear la tarea con mas procesadores si el cluster no reconoce los ranks ni los procesos?
Gracias

**Comment by rudyjb24** [comment]
Como lo hablamos en ayudantia, en el archivo job.sh deben eliminar la linea para pedir nodos, solo deben decir cuantos procesos quieren y asegurarse de correr el ejecutable con mpirun (no srun).

Ya esta actualizado el cluster con archivos job.sh que funcionan.
